---
apiVersion: v1
kind: Service
metadata:
  name: oncall-mysql-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
      protocol: TCP